### ISSUE TITLE
Error in compilation 

### ISSUE THREAD

**Issue by robsalasco** [qgis/homebrew-qgisdev#34]
Hi! I'm using the new brew formula on sierra. 

```
robsalasco@agafya:~$ brew install qgis3-dev
Updating Homebrew...
==> Installing qgis3-dev from qgis/qgisdev
==> Cloning https://github.com/qgis/QGIS.git
Updating /Users/robsalasco/Library/Caches/Homebrew/qgis3-dev--git
==> Checking out branch master
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-D
==> cmake --build . --target all -- -j 4
==> cmake --build . --target install -- -j 4
Last 15 lines from /Users/robsalasco/Library/Logs/Homebrew/qgis3-dev/03.cmake:
-- Installing: /usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/pyplugin_installer/ui_qgsplugininstallerpluginerrorbase.py
-- Installing: /usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/pyplugin_installer/ui_qgsplugininstallerrepositorybase.py
-- Installing: /usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/qgis/testing/__init__.py
-- Installing: /usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/qgis/testing/mocked.py
CMake Error at /tmp/qgis3-dev-20170818-96695-1v65hn4/cmake/MacBundleMacros.cmake:236 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  mac/0qgis.cmake:10 (INCLUDE)
  mac/cmake_install.cmake:35 (include)
  cmake_install.cmake:42 (include)


FAILED: CMakeFiles/install.util
cd /tmp/qgis3-dev-20170818-96695-1v65hn4/build && /usr/local/Cellar/cmake/3.9.1/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by phborba** [comment]
I'm also getting that problem :/

**Comment by phborba** [comment]
Today I got this error:
Philipes-MacBook-Pro:~ philipeborba$ brew install qgis3-dev
==> Installing qgis3-dev from qgis/qgisdev
==> Installing dependencies for qgis/qgisdev/qgis3-dev: expat
==> Installing qgis/qgisdev/qgis3-dev dependency: expat
==> Downloading https://homebrew.bintray.com/bottles/expat-2.2.4.sierra.bottle.t
######################################################################## 100,0%
==> Pouring expat-2.2.4.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS includes Expat 1.5.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/expat/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/expat/lib
    CPPFLAGS: -I/usr/local/opt/expat/include

==> Summary
🍺  /usr/local/Cellar/expat/2.2.4: 18 files, 429.8KB
==> Installing qgis/qgisdev/qgis3-dev
==> Cloning https://github.com/qgis/QGIS.git
Updating /Users/philipeborba/Library/Caches/Homebrew/qgis3-dev--git
==> Checking out branch master
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-D
==> cmake --build . --target all -- -j 4
Last 15 lines from /Users/philipeborba/Library/Logs/Homebrew/qgis3-dev/02.cmake:
[1326/4244] : && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG  -dynamiclib -Wl,-headerpad_max_install_names -Qunused-arguments -F/Library/Frameworks   -compatibility_version 2.99.0 -current_version 2.99.0 -o output/lib/libqgispython.2.99.0.dylib -install_name /tmp/qgis3-dev-20170821-96822-tazzn8/build/output/lib/libqgispython.2.99.0.dylib src/python/CMakeFiles/qgispython.dir/qgispython.cpp.o src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o -F/usr/local/opt/qca/lib  -L/tmp/qgis3-dev-20170821-96822-tazzn8/build/src/core  -L/tmp/qgis3-dev-20170821-96822-tazzn8/build/src/gui output/lib/qgis_core.framework/Versions/2.99/qgis_core /usr/local/Frameworks/Python.framework/Versions/3.6/Python output/lib/qgis_native.framework/Versions/2.99/qgis_native -framework ApplicationServices -framework CoreFoundation -framework IOKit -framework AppKit /usr/local/opt/qt/lib/QtXml.framework/QtXml /usr/local/opt/qt/lib/QtConcurrent.framework/QtConcurrent /usr/local/opt/qt/lib/QtPrintSupport.framework/QtPrintSupport /usr/local/opt/qt/lib/QtSvg.framework/QtSvg /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/QtWebKitWidgets /usr/local/opt/qt/lib/QtWidgets.framework/QtWidgets /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/QtWebKit /usr/local/opt/qt/lib/QtGui.framework/QtGui /usr/local/opt/qt/lib/QtNetwork.framework/QtNetwork /usr/local/opt/qt/lib/QtSql.framework/QtSql -framework qca-qt5 /usr/local/lib/libqt5keychain.dylib /usr/local/opt/proj/lib/libproj.dylib /usr/local/opt/geos/lib/libgeos_c.dylib /usr/local/opt/gdal2/lib/libgdal.dylib /usr/local/opt/spatialindex/lib/libspatialindex.dylib /usr/local/opt/expat/lib/libexpat.dylib /usr/local/opt/sqlite/lib/libsqlite3.dylib /usr/local/opt/libspatialite/lib/libspatialite.dylib /usr/local/opt/libzip/lib/libzip.dylib /usr/local/opt/qt/lib/QtPositioning.framework/QtPositioning /usr/local/opt/qt/lib/QtCore.framework/QtCore && :
[1327/4244] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -I. -I../src/core -I../src/core/auth -I../src/core/expression -I../src/core/geometry -I../src/core/raster -I../src/core/metadata -I../src/gui -I../src/gui/auth -Isrc/ui -Isrc/core -Isrc/gui -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qca/lib/qca-qt5.framework/Headers -isystem /usr/local/include/qt5keychain -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/lib/QtScript.framework/Headers -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fvisibility=hidden   -F/usr/local/opt/qca/lib  -fPIC -std=gnu++11 -MD -MT src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsconnection.cpp.o -MF src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsconnection.cpp.o.d -o src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsconnection.cpp.o -c ../src/providers/wms/qgswmsconnection.cpp
[1328/4244] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -I. -I../src/core -I../src/core/auth -I../src/core/expression -I../src/core/geometry -I../src/core/raster -I../src/core/metadata -I../src/gui -I../src/gui/auth -Isrc/ui -Isrc/core -Isrc/gui -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qca/lib/qca-qt5.framework/Headers -isystem /usr/local/include/qt5keychain -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/lib/QtScript.framework/Headers -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fvisibility=hidden   -F/usr/local/opt/qca/lib  -fPIC -std=gnu++11 -MD -MT src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o -MF src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o.d -o src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o -c ../src/providers/wms/qgswmsdataitems.cpp
FAILED: src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o 
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -I. -I../src/core -I../src/core/auth -I../src/core/expression -I../src/core/geometry -I../src/core/raster -I../src/core/metadata -I../src/gui -I../src/gui/auth -Isrc/ui -Isrc/core -Isrc/gui -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qca/lib/qca-qt5.framework/Headers -isystem /usr/local/include/qt5keychain -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/lib/QtScript.framework/Headers -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fvisibility=hidden   -F/usr/local/opt/qca/lib  -fPIC -std=gnu++11 -MD -MT src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o -MF src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o.d -o src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsdataitems.cpp.o -c ../src/providers/wms/qgswmsdataitems.cpp
In file included from ../src/providers/wms/qgswmsdataitems.cpp:26:
../src/providers/wms/qgswmssourceselect.h:20:10: fatal error: 'ui_qgswmssourceselectbase.h' file not found
#include "ui_qgswmssourceselectbase.h"
         ^
1 error generated.
[1329/4244] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -I. -I../src/core -I../src/core/auth -I../src/core/expression -I../src/core/geometry -I../src/core/raster -I../src/core/metadata -I../src/gui -I../src/gui/auth -Isrc/ui -Isrc/core -Isrc/gui -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qca/lib/qca-qt5.framework/Headers -isystem /usr/local/include/qt5keychain -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/lib/QtScript.framework/Headers -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fvisibility=hidden   -F/usr/local/opt/qca/lib  -fPIC -std=gnu++11 -MD -MT src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmscapabilities.cpp.o -MF src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmscapabilities.cpp.o.d -o src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmscapabilities.cpp.o -c ../src/providers/wms/qgswmscapabilities.cpp
[1330/4244] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -I. -I../src/core -I../src/core/auth -I../src/core/expression -I../src/core/geometry -I../src/core/raster -I../src/core/metadata -I../src/gui -I../src/gui/auth -Isrc/ui -Isrc/core -Isrc/gui -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qca/lib/qca-qt5.framework/Headers -isystem /usr/local/include/qt5keychain -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/lib/QtScript.framework/Headers -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -O2 -g -DNDEBUG -fvisibility=hidden   -F/usr/local/opt/qca/lib  -fPIC -std=gnu++11 -MD -MT src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsprovider.cpp.o -MF src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsprovider.cpp.o.d -o src/providers/wms/CMakeFiles/wmsprovider_a.dir/qgswmsprovider.cpp.o -c ../src/providers/wms/qgswmsprovider.cpp
[1331/4244] cd /tmp/qgis3-dev-20170821-96822-tazzn8/build/python && /usr/local/Cellar/cmake/3.9.1/bin/cmake -E echo && /usr/local/Cellar/cmake/3.9.1/bin/cmake -E touch /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/gui/sip_guipart0.cpp /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/gui/sip_guipart1.cpp /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/gui/sip_guipart2.cpp /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/gui/sip_guipart3.cpp && /usr/local/Cellar/sip/4.19.3_1/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -t WS_MACX -t Qt_5_9_1 -o -a /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/qgis.gui.api -I /usr/local/share/sip -j 4 -c /tmp/qgis3-dev-20170821-96822-tazzn8/build/python/gui -I /usr/local/share/sip/Qt5 -I /tmp/qgis3-dev-20170821-96822-tazzn8/python /tmp/qgis3-dev-20170821-96822-tazzn8/python/gui/gui.sip

ninja: build stopped: subcommand failed.

**Comment by palmerj** [comment]
ANy update on this. I'm getting this same error as well:

```
-- Installing: /usr/local/Cellar/qgis3-dev/2.99/QGIS.app/Contents/MacOS/../Resources/python/qgis/testing/mocked.py
CMake Error at /tmp/qgis3-dev-20170828-61753-4q8y5h/cmake/MacBundleMacros.cmake:236 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  mac/0qgis.cmake:10 (INCLUDE)
  mac/cmake_install.cmake:35 (include)
  cmake_install.cmake:42 (include)


FAILED: CMakeFiles/install.util
cd /tmp/qgis3-dev-20170828-61753-4q8y5h/build && /usr/local/Cellar/cmake/3.9.1/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed
```

**Comment by dakcarto** [comment]
Hi all,

I'm looking into this.

**Comment by dakcarto** [comment]
This bug is fixed upstream with https://github.com/qgis/QGIS/commit/8770625.

I'm also doing some updates to the `qgis3-dev` formula, unrelated to this fix.

**Comment by phborba** [comment]
@dakcarto unfortunately it still does not work for me =/

 I don't know whether this error I'm about to show is related to the updates you are doing, but anyway, 
here is part of the log:

Last 15 lines from /Users/philipeborba/Library/Logs/Homebrew/qgis3-dev/02.cmake:
                                                  ^
/usr/local/opt/qt/lib/QtCore.framework/Headers/qstring.h:117:51: error: expected ';' at end of declaration list
    inline bool operator<=(const QString &s) const Q_DECL_NOTHROW;
                                                  ^
/usr/local/opt/qt/lib/QtCore.framework/Headers/qstring.h:145:9: error: unknown type name 'QTypedArrayData'
typedef QTypedArrayData<ushort> QStringData;
        ^
/usr/local/opt/qt/lib/QtCore.framework/Headers/qstring.h:145:24: error: expected unqualified-id
typedef QTypedArrayData<ushort> QStringData;
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[4127/4418] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -Dgeorefplugin_EXPORTS -I. -I../src/plugins/georeferencer -I../src/core -I../src/core/expression -I../src/core/geometry -I../src/core/metadata -I../src/core/raster -I../src/core/composer -I../src/gui -I../src/gui/editorwidgets -I../src/gui/layertree -I../src/plugins -Isrc/core -Isrc/gui -Isrc/app -Isrc/ui -Isrc/plugins/georeferencer -isystem /usr/local/opt/gsl/include -isystem ../src/plugins/georeferencer/include/qgis -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qwt/lib/qwt.framework/Headers -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/include -isystem /usr/local/opt/qt/include/QtUiTools -isystem /usr/local/Cellar/grass7/7.2.1/grass-base/include -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -DNDEBUG -fPIC -fvisibility=hidden   -F/usr/local/opt/qca/lib -F/usr/local/opt/qwt/lib  -fPIC -std=gnu++11 -MD -MT src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgsvalidateddoublespinbox.cpp.o -MF src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgsvalidateddoublespinbox.cpp.o.d -o src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgsvalidateddoublespinbox.cpp.o -c src/plugins/georeferencer/moc_qgsvalidateddoublespinbox.cpp
[4128/4418] /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DQGISDEBUG=1 -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QTWEBKIT -Dgeorefplugin_EXPORTS -I. -I../src/plugins/georeferencer -I../src/core -I../src/core/expression -I../src/core/geometry -I../src/core/metadata -I../src/core/raster -I../src/core/composer -I../src/gui -I../src/gui/editorwidgets -I../src/gui/layertree -I../src/plugins -Isrc/core -Isrc/gui -Isrc/app -Isrc/ui -Isrc/plugins/georeferencer -isystem /usr/local/opt/gsl/include -isystem ../src/plugins/georeferencer/include/qgis -isystem /usr/local/opt/gdal2/include -isystem /usr/local/opt/geos/include -isystem /usr/local/opt/qwt/lib/qwt.framework/Headers -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtXml.framework/Headers -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtConcurrent.framework/Headers -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtPrintSupport.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -iframework /usr/local/opt/qt5-webkit/lib -isystem /usr/local/opt/qt5-webkit/lib/QtWebKit.framework/Headers -isystem /usr/local/opt/qt5-webkit/lib/QtWebKitWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtSql.framework/Headers -isystem /usr/local/opt/qt/lib/QtPositioning.framework/Headers -isystem /usr/local/opt/qt/include -isystem /usr/local/opt/qt/include/QtUiTools -isystem /usr/local/Cellar/grass7/7.2.1/grass-base/include -DSPATIALITE_VERSION_GE_4_0_0 -DSPATIALITE_VERSION_G_4_1_1 -DSPATIALITE_HAS_INIT_EX -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Qunused-arguments -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -DNDEBUG -fPIC -fvisibility=hidden   -F/usr/local/opt/qca/lib -F/usr/local/opt/qwt/lib  -fPIC -std=gnu++11 -MD -MT src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgstransformsettingsdialog.cpp.o -MF src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgstransformsettingsdialog.cpp.o.d -o src/plugins/georeferencer/CMakeFiles/georefplugin.dir/moc_qgstransformsettingsdialog.cpp.o -c src/plugins/georeferencer/moc_qgstransformsettingsdialog.cpp
ninja: build stopped: subcommand failed.

Thanks so much for your help!

**Comment by robsalasco** [comment]
@phborba open a new issue because the original bug now is fixed. 

Thank you @dakcarto!!!
