### ISSUE TITLE
QGIS not running in HiDPI by default on Retina display

### ISSUE THREAD

**Issue by nextstopsun** [qgis/homebrew-qgisdev#5]
A good reason to try out qgis3-dev is to get HiDPI support on OS X. I guess that wasn't possible for QT4-based versions, but ok for Qt5.
Could be great to have QGIS built with HiDPI enabled by default on retina displays.
Or maybe this should it be a configuration checkbox.

Meanwhile, how do I enable it manually?

**Comment by dakcarto** [comment]
Hi @nextstopsun, thanks for bringing this up. You can try the following:

1. Edit  `/usr/local/opt/qgis3-dev/QGIS.app/Contents/Info.plist`
2. Change `NSHighResolutionCapable` key to `True`, then save `Info.plist`
3. Run `touch /usr/local/opt/qgis3-dev/QGIS.app` to ensure launch services is notified of plist change

Looks like the `qgis3-dev` formula needs updated here, since it sets that key to False.

Note: I don't see any major changes here when I do that (this is a good thing). Also, the low resolution icon is due to a missing high-res one for Mac, not due to incompatible `NSHighResolutionCapable` settings.

**Comment by dakcarto** [comment]
If you change `NSHighResolutionCapable` as noted above, the Finder's Info dialog for the QGIS.app will now display the "Open in Low Resolution" checkbox, which _should_ be unchecked by default.

**Comment by nextstopsun** [comment]
@dakcarto Thanks. I'll try that. I'm mostly interested in getting map canvas display in HiDPI. 
BTW, are missing menu icons related to this one, or it's a separate issue?

**Comment by dakcarto** [comment]
> BTW, are missing menu icons related to this one, or it's a separate issue?

Separate issue, I think, possibly related to packaging and whether they are SVG or PNG. Haven't looked into it yet. Also here for me, the Options menu is replaced by the one from Processing. I'll work on fixing that upstream ASAP.

**Comment by nextstopsun** [comment]
According to window elements, qgis started in HiDPI mode, however map canvas seems to be in low res still. @dakcarto Are you getting this also?

**Comment by dakcarto** [comment]
> According to window elements, qgis started in HiDPI mode, however map canvas seems to be in low res still. @dakcarto Are you getting this also?

Sorry, don't have any more time right now to test. It may be that something in code has to be changed to fully enable HiDPI.

**Comment by m-kuhn** [comment]
Can you try to insert the following code in `src/gui/qgsmapcanvas.cpp` at line 585 (after `mSettings.setExpressionContext( expressionContext );`

    mSettings.setOutputDpi( logicalDpiX() );

**Comment by dakcarto** [comment]
If looking to edit QGIS source during a build of `qgis3-dev`, one will need to:

1. Edit the formula and put a `raise` statement just prior to the run of `cmake ...`
2. Build with `brew install qgis3-dev -dv` (or at least `-d`)
3. When `raise` is thrown, drop into a debug shell, edit the file, then `exit` debug shell
4. Choose to 'ignore' thrown `raise`, which will continue building

This is because any changes to `~/Library/Caches/Homebrew/qgis3-dev--git/*` will _probably_ be reset prior to building QGIS inside the formula.

```
...
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is behind 'origin/master' by 119 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
git reset --hard origin/master <-- !!!
...
```

Alternatively, @nextstopsun, you could [use the dependencies to do your own build](https://github.com/qgis/homebrew-qgisdev/tree/master/development).

**Comment by nextstopsun** [comment]
@dakcarto I have all the deps installed, I think I'm going to setup QT Creator build. On a second thought, what if I just clone master and edit the formula to build from a local repo?

**Comment by dakcarto** [comment]
> On a second thought, what if I just clone master and edit the formula to build from a local repo?

@nextstopsun that should work, though I recommend adding a `revision 1` just under `version "2.99"` and then use `brew upgrade -dv qgis3-dev`, so you do not loose your current build. Later, you can just `brew uninstall qgis3-dev` to clear the most recent, edited build.

Qt Creator setup is better and will be added soon to the tutorial.

**Comment by m-kuhn** [comment]
If anyone can test this patch, that would be much appreciated.

https://github.com/qgis/QGIS/pull/3847

**Comment by brncsk** [comment]
@m-kuhn No changes for me: UI chrome shows up in high res when `NSHighResolutionCapable` is set, but the map canvas is still rendering pixelated.

**Comment by m-kuhn** [comment]
@brncsk any chance you could find the value reported by `logicalDpiX()` - either with a debugger or temporarily add

    qWarning() << "Logical DPI X " << logicalDpiX();

**Comment by brncsk** [comment]
will try later today

**Comment by brncsk** [comment]
@m-kuhn:

`logicalDpiX()` reports `72`.
`physicalDpiX()` reports `111`, though, which yields a somewhat better, albeit still suboptimal result.

I also tried multiplying that by `devicePixelRatio() == 2` but it still feels a bit rough.

**Comment by brncsk** [comment]
In fact, increasing the argument of `setOutputDpi()` only seems to increase outline width (given in millimeters) and label font size (given in pts) but does not help with the rendering problem itself.

Screenshots at different `setOutputDpi()` resolutions:

72 (`logicalDpiX()`):
<img width="431" alt="72" src="https://cloud.githubusercontent.com/assets/1205180/21011080/daba2ac8-bd4f-11e6-8233-dd7f8b847feb.png">

111 (`physicalDpiX()`):
<img width="441" alt="111" src="https://cloud.githubusercontent.com/assets/1205180/21011082/db0da9fa-bd4f-11e6-96b8-124256b693ef.png">

222 (`physicalDpiX() * devicePixelRatio()`):
<img width="452" alt="222" src="https://cloud.githubusercontent.com/assets/1205180/21011083/db0e3244-bd4f-11e6-8fd2-4d4875f575c8.png">

444 (`physicalDpiX() * devicePixelRatio() * 2`):
<img width="707" alt="444" src="https://cloud.githubusercontent.com/assets/1205180/21011084/db0e4cd4-bd4f-11e6-833e-fafe62a161da.png">

**Comment by m-kuhn** [comment]
> In fact, increasing the argument of setOutputDpi() only seems to increase outline width

Correct, that's exactly what needs to be done in the rendering engine - but each pixel of the screen should be used (I guess now there are 4 equal pixels sitting next to each other on your map).

There's an issue in Qt with QGraphicsView and HiDpi: https://bugreports.qt.io/browse/QTBUG-26795 but it looks like caching is not explicitly enabled and defaults to disabled and I don't think we use the GL version, so this shouldn't affect us.

**Comment by dakcarto** [comment]
Hi. Can someone retest the rendering issue with latest `qgis3-dev`, which now fully builds against Qt 5.8.0? See known issues in #22.

Fixed with Qt 5.8.0: SVG menu icons now show properly (sweet!).

Also, I have [updated the dock and app switcher icon](https://github.com/qgis/QGIS/commit/35edc182ea20eca6b3ae16defce5557f21b390a2) to 1024x1024.

**Comment by brncsk** [comment]
It does not seem to fix the rendering issue, output is still pixellated. The 1024x1024 icon is a nice touch, though!

**Comment by Malauch** [comment]
I just want to report, that problem with pixelated output on canvas is still here. In addition plugin description (in plugin manager window) is oversized.
<img width="428" alt="zrzut ekranu 2017-11-08 o 09 46 26" src="https://user-images.githubusercontent.com/13001524/32539520-fbc8ef66-c469-11e7-8941-46002e6c5fd6.png">
<img width="1434" alt="zrzut ekranu 2017-11-08 o 09 04 48" src="https://user-images.githubusercontent.com/13001524/32539523-fd9aef74-c469-11e7-9265-4f5f49a72fc8.png">

**Comment by dakcarto** [comment]
Hi. I am closing this as it is an issue to be discussed on the main QGIS issue tracker:
https://issues.qgis.org

I believe I have done what can be via the Homebrew formula and something more needs addressed in the core codebase.

**Comment by dakcarto** [comment]
This is the only current issue of similar topic I could find:
https://issues.qgis.org/issues/15357

**Comment by dakcarto** [comment]
I also created a saved query on the tracker for "Subjects with dpi":
https://issues.qgis.org/projects/qgis/issues?query_id=145
